### ISSUE TITLE
Blocks concertina'd shut by default

### ISSUE THREAD

**Issue by arctangent** [noripyt/wagtail-react-streamfield#13]
We would like to be able to control which ones are open and which are closed by default

**Comment by BertrandBordage** [comment]
Yes, this is one of the upcoming features :)

**Comment by ladrua** [comment]
Is it possible to have all open by default in todays version?

**Comment by BertrandBordage** [comment]
Since 1.0.0, released today, the default layout is `SIMPLE`, a layout closer to the old StreamField where there is no way to collapse blocks. Blocks can still be defined as using the `COLLAPSIBLE` layout by writing:
```python
class YourBlock(CharBlock):
    def get_layout(self):
        return self.COLLAPSIBLE
```

That being said, you may want to keep `COLLAPSIBLE` blocks, but opened by default.

To do that, use this:
```python
class YourBlock(CharBlock):
    def get_layout(self):
        return self.COLLAPSIBLE

    def get_definition(self):
        definition = super().get_definition()
        definition['closed'] = False
        return definition
```
