### ISSUE TITLE
The new duplicate icon is missleading

### ISSUE THREAD

**Issue by tobiase** [noripyt/wagtail-react-streamfield#24]
![wagtail bearbeite functions page funktionen](https://user-images.githubusercontent.com/487379/49604076-3cc44200-f98d-11e8-8d00-88bebca00066.png)

**Comment by BertrandBordage** [comment]
Yes, I of course know about that :) I took this icon because it requires to rebuild the icon font from Wagtail, and I currently don’t fully understand how to edit the wagtail.woff font. It seems to be generated with https://icomoon.io/app/, and using it I manage to parse the existing font and regenerate it, but not yet import another glyph for the duplication.
I’ll try again shortly.

**Comment by BertrandBordage** [comment]
Fixed by c113bda36335a30f73529430aef6ff07f7cfddda.

In the end I rebuilt an icon myself, based on the doc-full icon.

**Comment by mariod3w** [comment]
Hello @BertrandBordage 

Icon duplicate not work in 2.9 versión.

Can you help me? 

Thanks
