### ISSUE TITLE
DateBlock can't be serialized to JSON

### ISSUE THREAD

**Issue by hoganld** [noripyt/wagtail-react-streamfield#6]
Hi @BertrandBordage , I love what I see from this package so far. I've hit one issue with rendering a DateBlock in the Wagtail admin. If the DateBlock has a `None` value, all is well, but if it has a date value, the template throws a 500 at `render_with_errors`. I tracked the issue down to `widgets.InputJSONEncoder`, and also found a patch for a similar issue [with wagtail-condensedinlinepanel](https://github.com/wagtail/wagtail-condensedinlinepanel/pull/36/commits/df28954311504cbedf5eb710e87ff611bb1f25a7). I'm curious if you've seen the same thing at any point, or if you can reproduce the issue?

For the time being, I've submitted a proof-of-concept patch in [this PR](https://github.com/noripyt/wagtail-react-streamfield/pull/5), for you to consider.

**Comment by BertrandBordage** [comment]
Fixed by 4d4e574fa2df55d8c3befe54719bab262d40943d.

This was not the same issue as in wagtail-condensedinlinepanel.
I could make a clean non-Wagtail-specific solution :slightly_smiling_face:
Unfortunately, because the `change` event is not correctly triggered by the widget, I had to amend the picker JavaScript as well.
